# Generated by Django 4.0.1 on 2022-01-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wordy", "0003_alter_document_full_text")]

    operations = [
        migrations.AlterField(
            model_name="document", name="full_text", field=models.TextField()
        )
    ]
